import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter, Roboto, Poppins } from "next/font/google";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/context/ThemeContext";
// import ScrollToTopButton from "@/components/ScrollToTopButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "GavvyWeb",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <div className="z-50">
            <Navbar />
          </div>
          <div className="container z-20">
            {children}
            {/* <ScrollToTopButton /> */}
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}

// {
//   <div ref={ref} className="container overflow-hidden">
//     <motion.div
//       variants={{
//         hidden: { opacity: 0, y: 75 },
//         visible: { opacity: 1, y: 0 },
//       }}
//       initial="hidden"
//       animate={mainControls}
//       transition={{ duration: 0.5, delay: 0.25 }}
//     >
//       {children}
//     </motion.div>
//     {/* <ScrollToTopButton /> */}
//     <Footer />
//   </div>;
// }
